-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "supplier" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "minStockLevel" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "maxStockLevel" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "lastRestockedAt" TIMESTAMP(3);
